---
- hosts: web
  vars:
    db_password: password
    server_name: curriculum
    service_name: curriculum
    service_version: 1.0
    app_key: QujjaJs3fxwtnTl7FiqhEEn1ACkf7YZW
    app_env: test
    db_host: localhost
    db_database: curriculum
    db_username: curriculum
    db_port: 3306
    service_dir: /usr/share/nginx/{{ service_name }}
  tasks:
  - name: "Change SELinux to permissive"
    become: yes
    lineinfile:
      dest: /etc/sysconfig/selinux
      regexp: '^SELINUX='
      line: 'SELINUX=permissive'

  - name: Again change SELinuz to permissive
    become: yes
    command: setenforce 0

  - name: Install the epel repo
    become: yes
    yum:
      name: epel-release
      update_cache: yes
      state: present

  - name: Install nginx, php and related packages
    become: yes
    yum:
      update_cache: yes
      state: present
      name: {{ item }}
      with_items:
        - nginx
        - php
        - php-fpm
        - php-ldap
        - php-mbstring
        - php-mcrypt
        - php-mysql
        - php-phpunit-PHPUnit
    register: nginx_install

  - name: Download Composer #provided by Vinelab/ansible-composer
    become: yes
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/installer

  - name: Install Composer
    become: yes
    shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
    args:
      creates: /usr/local/bin/composer

  - name: rename composer.phar to composer
    become: yes
    shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    args:
      creates: /usr/local/bin/composer

  - name: make composer executable
    file:
      path: /usr/local/bin/composer
      mode: a+x
      state: file

  - name: Replace the nginx.conf file
    copy:
      src: web/nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
    become: yes
    register: nginx_conf

  - name: configuring the specific website, vhost_conf
    become: yes
    template:
      src: web/vhost.conf.j2
      dest: /etc/nginx/conf.d/{{ service_name }}.conf
      mode: 0644
    register: vhost_conf

  - name: adding the php.ini file
    become: yes
    template:
      src: web/php.ini.j2
      dest: /etc/php.ini
      mode: 0644
    register: php_conf

  - name: copy php-fpm-web.conf to www.conf
    become: yes
    copy:
      src: web/php-fpm-web.conf
      dest: /etc/php-fpm.d/www.conf
      mode: 0644
    register: php_fpm_conf

  - name: Restart nginx if changes were made to nginx related files
    become: yes
    service: #changed from systemd to service due to version issues
      name: nginx
      state: restarted
      enabled: yes
    when: nginx_install|changed or nginx_conf|changed or vhost_conf|changed

  - name: Restart php if there are changes made to the files
    become: yes
    service:
      name: php-fpm
      state: restarted
      enabled: yes
    when: nginx_install|changed or php_conf|changed or php_fpm_conf|changed

  - name: "4 "
    become: yes
    file: path={{ service_dir }} state=absent

  - name: "4a"
    become: yes
    file: path={{ service_dir }} state=directory

  - name: decompress the info from web
    become: yes
    unarchive:
      src: web/{{ service_name }}.tgz
      dest: {{ service_dir }}
      mode: 0755

  - name: "6 "
    become: yes
    command: /usr/local/bin/composer update chdir={{ service_dir }}

  - name: "7 "
    become: yes
    command: chmod -R 0777 storage chdir={{ service_dir }}

  - name: "8 "
    become: yes
    command: chown nginx:nginx "{{ service_dir }}" -R

  - name: "9 "
    become: yes
    template:
      src: web/env.j2
      dest: "{{ service_dir }}/.env"
      mode: 0644
      owner: nginx
